PREFIX cimd: <https://cim.ucaiug.io/diagrams#>
select ?kind ?mrids ?link {
  graph ?g {
    ?x a cimd:Diagram; 
      cimd:Diagram.kind ?kindUrl;
      cimd:Diagram.link ?link.
    optional {?x cimd:Diagram.mRIDs ?mrids}
    bind(strafter(str(?kindUrl),"PowSyBl-") as ?kind)
  }
} order by ?link
